### PR TITLE
chore(language-map): add `pacscript` file

### PR DESCRIPTION
**Pull request by Henryws**

### CODE REVIEW

**Comment by meche-gh** [comment]
Have a read of https://github.com/PKief/vscode-material-icon-theme/blob/main/CONTRIBUTING.md#add-new-icons
You should be able to open this pull in there and it'll get picked up automatically here.

**Comment by Henryws** [comment]
I'm not adding a new icon, just making it aware of a file format that uses shell.

**Comment by meche-gh** [comment]
https://github.com/PKief/vscode-material-icon-theme/commits/f12fc4973762b713e1fc39347a6760ed9210eaf7

**Comment by Claudiohbsantos** [comment]
Hey @Henryws . Thanks for the contribution, and I'm sorry it took me so long to get back to you. It looks like this has been resolved upstream, right? If so I'll close this pull request already

**Comment by zm-cttae** [comment]
@Henryws you can follow these instructions in core repository to add `pacscript` support: [# "File icons"](https://github.com/PKief/vscode-material-icon-theme/blob/main/CONTRIBUTING.md#file-icons)

**Pull request closed without merging**
