### PR TITLE
visualstudio.com support

### LINKED ISSUE #40: Support `visualstudio.com` url for Azure Repos
I think this should be a fairly straightforward addition to the switch statement

### PR DESCRIPTION
**Pull request by csandman**
- Add support for the Azure provider on "visualstudio.com" URLs - closes #40 

I figured I might as well make a PR for this as I made the original provider haha.  I can't really test it as I don't have access to a visualstudio.com azure devops repo, but I can't see why this wouldn't work

### CODE REVIEW

**Comment by jamiehaywood** [comment]
I've tried testing & it doesn't seem to be working. It must be a selector that's slightly different. I've got a visualstudio repo for you to test on: https://jamieadhaywood.visualstudio.com/Test/_git/Test

**Comment by jamiehaywood** [comment]
I will try and have a look into it this weekend, given I was the feature requester :D

**Comment by csandman** [comment]
It looks like I missed the `*.` at the beginning of the URL matches in the manifest, can you give my most recent push a try?  The URL you provided seems to be working for me!

**Comment by jamiehaywood** [comment]
image
can confirm this is working. ready to merge I think 😄 
what do you think @Claudiohbsantos ?

**Review by Claudiohbsantos — APPROVED** [review]
This is perfect, short and simple:) Thanks for jumping on this @csandman  and @jamiehaywood  

Looks good to me. I'm going to approve already and hold the merge for a sec until I figure out the best way to avoid spamming users with permission change notifications. I'll aim to merge this week along with the other approved PR.

**Pull request merged**
